### ISSUE TITLE
Inaccessible private memory regions

### ISSUE THREAD

**Issue by Urahara3000** [Alexx999/Dumper#1]
The program works fine, except that it is not allowed to the private regions of the process memory, would you like to add this permission to be able to access the privileged regions of the memory ?

**Comment by Alexx999** [comment]
By "private regions" you mean ones protected by VirtualProtectEx?
I can't see such permission - there's no flag that gives access level higher than PROCESS_VM_READ. I guess that to read those you need to unprotect them first, then save data, then restore protection settings.
Also, there are "protected processes" that need some special hacks to read (driver maybe? surely beyond the scope of normal WinAPI).

**Comment by Urahara3000** [comment]
I think it's VirtualProtectEx because the problem occurs with the Playstation 3 emulator (RPCS3) and the Nintendo 3DS emulator (Citra), if you can do a test on any of these emulators you could analyze the problem, if you solve this problem, the program will be perfect, if you have a free time of course, stay with God and until next time.

**Comment by Alexx999** [comment]
Indeed, RPCS3 loves PAGE_NOACCESS modifier for some reason - it's used widely in there

**Comment by Urahara3000** [comment]
And with this PAGE_NOACCESS modifier is it impossible to read this particular area ?

**Comment by Alexx999** [comment]
Should work now
